package com.beanbrew.entity;

public enum AlertType {
    LOW_WATER, LOW_MILK, LOW_COFFEE_POWDER, HIGH_TEMPERATURE, LOW_TEMPERATURE,
    NO_DISPENSING, REPEATED_ERRORS, MACHINE_OFFLINE, NETWORK_DISCONNECTION,
    HEATER_FAILURE, ABNORMAL_BEHAVIOUR
}
